### ISSUE TITLE
Error importing Fit in Python 3

### ISSUE THREAD

**Issue by Federico2111** [vgm64/python-fit#4]
Hello,

I am experiencing problems importing the Fit package in my Python script. 

When I was using Python 2, the script was running. Now, I have upgraded Python to the latest version and I get the following error:

**import fit
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fit/__init__.py", line 53
    raise exc_type, exc_val, exc_tb
                  ^
SyntaxError: invalid syntax**

What would you suggest? 

The Fit library is correctly installed on Python 3.

Please, let me know. 

Thanks

**Comment by Federico2111** [comment]
Did someone solve this issue?

**Comment by vgm64** [comment]
Looking at the error, `site-packages/fit/init.py` is concerning because that is not a file in this repo. Can you post your installation steps to reproduce the issue?

**Comment by Federico2111** [comment]
The installation goes fine, I get the error when I run my script with Python 3. It didn't use to happen with Python 2. Was the syntax of your library updated to Python 3?

Thanks for your help.

**Comment by vgm64** [comment]
It wasn't, and I can push a branch to do so, but I'd like if I could reproduce on my end for debugging to shorten the development cycle.

Can you share your full installation & error text? Minimum example to reproduce the error would be great. For me, a fresh virtual environment and a pop install of this package produces a different error (print syntax error) so you may be facing a different issue entirely. It may be a packaging issue if file names aren't lining up.

**Comment by Federico2111** [comment]
This is what I get when I install the fit library again:

MacBook-Pro-di-federico-2:~ fede$ pip3 install python-fit
Requirement already satisfied: python-fit in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (1.0.0)

This is what I get when I run my script: 

MacBook-Pro-di-federico-2:Statistical_Tests fede$ python3 Dep_1-Tailed_Test.py 
Traceback (most recent call last):
  File "Dep_1-Tailed_Test.py", line 29, in <module>
    import fit
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/fit/__init__.py", line 53
    raise exc_type, exc_val, exc_tb
                  ^
SyntaxError: invalid syntax

**Comment by vgm64** [comment]
Can you stick the following into a bash script, run it, and post the output? 

```
rm -rf testing_ground

mkdir testing_ground
cd testing_ground

virtualenv virtualenv_for_testing

. virtualenv_for_testing/bin/activate

echo `which python`
echo `python --version`

pip install python-fit
pip install scipy

python -c 'import fit'
```

**Comment by Federico2111** [comment]
If I put your text in a script (test.py) and run it, this is what I get: 

MacBook-Pro-di-federico-2:Desktop fede$ python3 test.py
  File "test.py", line 1
    rm -rf testing_ground
                        ^
SyntaxError: invalid syntax





If I run your text from my bash, this is what I get:

MacBook-Pro-di-federico-2:testing_ground fede$ rm -rf testing_ground
MacBook-Pro-di-federico-2:testing_ground fede$ 
MacBook-Pro-di-federico-2:testing_ground fede$ mkdir testing_ground
MacBook-Pro-di-federico-2:testing_ground fede$ cd testing_ground
MacBook-Pro-di-federico-2:testing_ground fede$ 
MacBook-Pro-di-federico-2:testing_ground fede$ virtualenv virtualenv_for_testing
-bash: virtualenv: command not found
MacBook-Pro-di-federico-2:testing_ground fede$ 
MacBook-Pro-di-federico-2:testing_ground fede$ . virtualenv_for_testing/bin/activate
-bash: virtualenv_for_testing/bin/activate: No such file or directory
MacBook-Pro-di-federico-2:testing_ground fede$ 
MacBook-Pro-di-federico-2:testing_ground fede$ echo `which python`
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
MacBook-Pro-di-federico-2:testing_ground fede$ echo `python --version`
Python 2.7.9

MacBook-Pro-di-federico-2:testing_ground fede$ 
MacBook-Pro-di-federico-2:testing_ground fede$ pip install python-fit
Requirement already satisfied: python-fit in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (1.0.0)
MacBook-Pro-di-federico-2:testing_ground fede$ pip install scipy
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (1.5.3)
Requirement already satisfied: numpy>=1.14.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from scipy) (1.17.0)
MacBook-Pro-di-federico-2:testing_ground fede$ 
MacBook-Pro-di-federico-2:testing_ground fede$ python -c 'import fit'

**Comment by vgm64** [comment]
Can you put it in a script called `run_tesh.sh` and run it with `bash run_test.sh`?

**Comment by Federico2111** [comment]
MacBook-Pro-di-federico-2:Desktop fede$ bash run_test.sh
run_test.sh: line 6: virtualenv: command not found
run_test.sh: line 8: virtualenv_for_testing/bin/activate: No such file or directory
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
Python 2.7.9

Requirement already satisfied: python-fit in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (1.0.0)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (1.5.3)
Requirement already satisfied: numpy>=1.14.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from scipy) (1.17.0)

**Comment by vgm64** [comment]
Can you execute `pip install virtualenv` and re-run?

**Comment by Federico2111** [comment]
MacBook-Pro-di-federico-2:Desktop fede$ bash run_test.sh
created virtual environment CPython3.7.4.final.0-64 in 1029ms
  creator CPython3Posix(dest=/Users/fede/Desktop/testing_ground/virtualenv_for_testing, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/fede/Library/Application Support/virtualenv)
    added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
/Users/fede/Desktop/testing_ground/virtualenv_for_testing/bin/python
Python 3.7.4
Collecting python-fit
  Using cached python-fit-1.0.0.tar.gz (6.6 kB)
Building wheels for collected packages: python-fit
  Building wheel for python-fit (setup.py) ... done
  Created wheel for python-fit: filename=python_fit-1.0.0-py3-none-any.whl size=6785 sha256=9e62bac4c670ec6ff85380d5c5ce2a930844ac270ccc79630706bc5aa7ee37d3
  Stored in directory: /Users/fede/Library/Caches/pip/wheels/2d/4c/fe/9123910c8a414fd951360f8bb45fe6ed21130a0fc6f4f9b78c
Successfully built python-fit
Installing collected packages: python-fit
Successfully installed python-fit-1.0.0
Collecting scipy
  Downloading scipy-1.5.4-cp37-cp37m-macosx_10_9_x86_64.whl (28.7 MB)
     |████████████████████████████████| 28.7 MB 533 kB/s 
Collecting numpy>=1.14.5
  Downloading numpy-1.19.4-cp37-cp37m-macosx_10_9_x86_64.whl (15.3 MB)
     |████████████████████████████████| 15.3 MB 1.1 MB/s 
Installing collected packages: numpy, scipy
Successfully installed numpy-1.19.4 scipy-1.5.4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fede/Desktop/testing_ground/virtualenv_for_testing/lib/python3.7/site-packages/fit.py", line 260
    print '(WWW) poly_lsq: Iteration limit reached, result not reliable!'
                                                                        ^
SyntaxError: invalid syntax

**Comment by vgm64** [comment]
I pushed a change to github. Would you be able to clone the repo and check on your end if it works?

**Comment by Federico2111** [comment]
Not sure I know how to do it...
